about_widget_content = "Machine Learning Enthusiast, Artificial Intelligence developer, researcher, practitioner"
address = "Rangpur, Bangladesh"
author = "Rakib Hossain Sajib"
contact_form_action = "#"
copyright = "Copyright ©2020. All Rights Reserved."
custom_script = ""
description = "Welcome"
email = "rakibnsajib@gmail.com"
favicon = "images/favicon.png"
featured_post_title = "Featured Post"
footer_content = "“If you only do what you can do, you will never be more than who you are.”  ― Master Shifu"
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = "+8801823517770"
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "Is Machine Learning Enthusiast and is an Artificial Intelligence developer, researcher, practitioner"
enable = true
image = "images/banner.png"
title_large = "Welcome **!**"
title_small = "to Sajib Blog"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/rakibnsajib.brur/"
title = "facebook"
[[social]]
icon = "fab fa-github"
link = "https://github.com/RakibNSajib"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/rakibnsajib/"
title = "linkedin"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-telegram"
link = "https://t.me/rakibnsajib"
title = "Telegram"
